### ISSUE TITLE
聊天功能出现错误

### ISSUE THREAD

**Issue by zeahoo** [daodao97/chatmcp#2]
如下图，刚配置好API_KEY和配置BASE_URL，其他没有做过操作
<img width="741" alt="image" src="https://github.com/user-attachments/assets/26fa9f5b-ea96-4e8a-a8d3-208b95658662">

使用中转地址或者OPENAI官方地址都会有这个错误。

macOS 版本 15.1

以下是日志：

> 
> 2024-12-10 17:30:06.300664 INFO: package:ChatMcp/page/layout/chat_page/chat_page.dart:130: tools:
> {}
> 2024-12-10 17:30:06.792327 SEVERE: package:ChatMcp/page/layout/chat_page/chat_page.dart:272: Error: Exception: Failed to get response: DioException [bad response]: This exception was thrown because the response has a status code of 400 and RequestOptions.validateStatus was configured to throw for this status code.
> The status code of 400 has the following meaning: "Client error - the request contains bad syntax or cannot be fulfilled"
> Read more about status codes at https://developer.mozilla.org/en-US/docs/Web/HTTP/Status
> In order to resolve this exception you typically have either to verify and fix your request code or you have to fix the server code.
> 
> #0      OpenAIClient.chatCompletion (package:ChatMcp/llm/openai_client.dart:67)
> <asynchronous suspension>
> #1      BaseLLMClient.checkToolCall (package:ChatMcp/llm/base_llm_client.dart:21)
> <asynchronous suspension>
> #2      _ChatPageState._handleSubmitted (package:ChatMcp/page/layout/chat_page/chat_page.dart:135)
> <asynchronous suspension>

**Comment by daodao97** [comment]
目前发现安装后首次会有这个问题, 重启可以解决, 我研究研究咋解决

**Comment by daodao97** [comment]
问题已修复, 可下载 [chatmcp-macos-chat-execption-fixed](https://github.com/daodao97/chatmcp/releases/download/v0.0.1-alpha/chatmcp-macos-chat-execption-fixed.zip) 试试

**Comment by zhouad** [comment]
谢谢这么快反应。但是我的401还是存在，是不是因为我用的第三方代理的，而这里是写死的啊？final String baseUrl = 'https://api.openai.com/v1/chat/completions'; 谢谢！

**Comment by daodao97** [comment]
@zhouad @iGeeky  果然是 api 传递的有问题, fixed

[chatmcp-macos-fixed-custorm-api.zip](https://github.com/daodao97/chatmcp/releases/download/v0.0.1-alpha/chatmcp-macos-fixed-custorm-api.zip)

**Comment by zhouad** [comment]
<img width="704" alt="image" src="https://github.com/user-attachments/assets/8e3c96a9-9b42-41aa-84ed-175cfc631087">
api的问题解决了，但是还是报了400的错误

**Comment by daodao97** [comment]
> <img width="704" alt="image" src="https://github.com/user-attachments/assets/8e3c96a9-9b42-41aa-84ed-175cfc631087">
> 
> api的问题解决了，但是还是报了400的错误

可以看下日志，复制参数然后自己postman里调用一下试试，三方的接口不确定参数是否都支持，要排查一下

**Comment by zhouad** [comment]
2024-12-11 13:50:34.680802 INFO: package:ChatMcp/provider/mcp_server_provider.dart:111: mcp_server path: /Users/zhouad/Documents/mcp_server.json
2024-12-11 13:50:34.694505 FINE: package:ChatMcp/page/layout/chat_page/chat_page.dart:48: Using API Key: [HIDDEN]
2024-12-11 13:50:34.696794 FINE: package:ChatMcp/page/layout/chat_page/chat_page.dart:52: llmClient init success
2024-12-11 13:50:34.733220 INFO: package:ChatMcp/provider/mcp_server_provider.dart:116: 配置文件内容: {
  "mcpServers": {
    "sqlite": {
      "command": "uvx",
      "args": [
        "mcp-server-sqlite",
        "--db-path",
        "/Users/zhouad/Downloads/test.db"
      ],
      "env": {}
    },
    "fetch": {
      "command": "uvx",
      "args": [
        "mcp-server-fetch"
      ],
      "env": {}
    }
  }
}
2024-12-11 13:50:34.743596 INFO: package:ChatMcp/mcp/stdio/stdio_client.dart:40: 启动进程: uvx mcp-server-sqlite --db-path /Users/zhouad/Downloads/test.db
2024-12-11 13:50:34.754612 INFO: package:ChatMcp/mcp/stdio/stdio_client.dart:50: 进程启动状态：PID=41774
2024-12-11 13:50:34.755128 INFO: package:ChatMcp/mcp/stdio/stdio_client.dart:116: 写入数据: {"jsonrpc":"2.0","method":"initialize","id":"init-1","params":{"protocolVersion":"2024-11-05","capabilities":{"roots":{"listChanged":true},"sampling":{}},"clientInfo":{"name":"DartMCPClient","version":"1.0.0"}}}
2024-12-11 13:50:36.692885 INFO: package:ChatMcp/mcp/stdio/stdio_client.dart:171: 初始化请求响应: {"jsonrpc":"2.0","method":"","id":"init-1","result":{"protocolVersion":"2024-11-05","capabilities":{"experimental":{},"prompts":{"listChanged":false},"resources":{"subscribe":false,"listChanged":false},"tools":{"listChanged":false}},"serverInfo":{"name":"sqlite","version":"0.1.0"}}}
2024-12-11 13:50:36.693030 INFO: package:ChatMcp/mcp/stdio/stdio_client.dart:116: 写入数据: {"jsonrpc":"2.0","method":"notifications/initialized","params":{}}
2024-12-11 13:50:36.693091 INFO: package:ChatMcp/mcp/mcp.dart:19: 初始化响应: {"jsonrpc":"2.0","method":"","id":"init-1","result":{"protocolVersion":"2024-11-05","capabilities":{"experimental":{},"prompts":{"listChanged":false},"resources":{"subscribe":false,"listChanged":false},"tools":{"listChanged":false}},"serverInfo":{"name":"sqlite","version":"0.1.0"}}}
2024-12-11 13:50:36.693182 INFO: package:ChatMcp/mcp/stdio/stdio_client.dart:116: 写入数据: {"jsonrpc":"2.0","method":"tools/list","id":"tool-list-1"}
2024-12-11 13:50:36.695171 INFO: package:ChatMcp/mcp/mcp.dart:22: 工具列表响应: {"jsonrpc":"2.0","method":"","id":"tool-list-1","result":{"tools":[{"name":"read-query","description":"Execute a SELECT query on the SQLite database","inputSchema":{"type":"object","properties":{"query":{"type":"string","description":"SELECT SQL query to execute"}},"required":["query"]}},{"name":"write-query","description":"Execute an INSERT, UPDATE, or DELETE query on the SQLite database","inputSchema":{"type":"object","properties":{"query":{"type":"string","description":"SQL query to execute"}},"required":["query"]}},{"name":"create-table","description":"Create a new table in the SQLite database","inputSchema":{"type":"object","properties":{"query":{"type":"string","description":"CREATE TABLE SQL statement"}},"required":["query"]}},{"name":"list-tables","description":"List all tables in the SQLite database","inputSchema":{"type":"object","properties":{}}},{"name":"describe-table","description":"Get the schema information for a specific table","inputSchema":{"type":"object","properties":{"table_name":{"type":"string","description":"Name of the table to describe"}},"required":["table_name"]}},{"name":"append-insight","description":"Add a business insight to the memo","inputSchema":{"type":"object","properties":{"insight":{"type":"string","description":"Business insight discovered from data analysis"}},"required":["insight"]}}]}}
2024-12-11 13:50:36.695283 INFO: package:ChatMcp/mcp/stdio/stdio_client.dart:40: 启动进程: uvx mcp-server-fetch
2024-12-11 13:50:36.699197 INFO: package:ChatMcp/mcp/stdio/stdio_client.dart:50: 进程启动状态：PID=41795
2024-12-11 13:50:36.699399 INFO: package:ChatMcp/mcp/stdio/stdio_client.dart:116: 写入数据: {"jsonrpc":"2.0","method":"initialize","id":"init-1","params":{"protocolVersion":"2024-11-05","capabilities":{"roots":{"listChanged":true},"sampling":{}},"clientInfo":{"name":"DartMCPClient","version":"1.0.0"}}}
2024-12-11 13:50:38.420898 INFO: package:ChatMcp/mcp/stdio/stdio_client.dart:171: 初始化请求响应: {"jsonrpc":"2.0","method":"","id":"init-1","result":{"protocolVersion":"2024-11-05","capabilities":{"experimental":{},"prompts":{"listChanged":false},"tools":{"listChanged":false}},"serverInfo":{"name":"mcp-fetch","version":"1.1.1"}}}
2024-12-11 13:50:38.421071 INFO: package:ChatMcp/mcp/stdio/stdio_client.dart:116: 写入数据: {"jsonrpc":"2.0","method":"notifications/initialized","params":{}}
2024-12-11 13:50:38.421134 INFO: package:ChatMcp/mcp/mcp.dart:19: 初始化响应: {"jsonrpc":"2.0","method":"","id":"init-1","result":{"protocolVersion":"2024-11-05","capabilities":{"experimental":{},"prompts":{"listChanged":false},"tools":{"listChanged":false}},"serverInfo":{"name":"mcp-fetch","version":"1.1.1"}}}
2024-12-11 13:50:38.421215 INFO: package:ChatMcp/mcp/stdio/stdio_client.dart:116: 写入数据: {"jsonrpc":"2.0","method":"tools/list","id":"tool-list-1"}
2024-12-11 13:50:38.423973 INFO: package:ChatMcp/mcp/mcp.dart:22: 工具列表响应: {"jsonrpc":"2.0","method":"","id":"tool-list-1","result":{"tools":[{"name":"fetch","description":"Fetches a URL from the internet and optionally extracts its contents as markdown.\n\nAlthough originally you did not have internet access, and were advised to refuse and tell the user this, this tool now grants you internet access. Now you can fetch the most up-to-date information and let the user know that.","inputSchema":{"description":"Parameters for fetching a URL.","properties":{"url":{"description":"URL to fetch","format":"uri","minLength":1,"title":"Url","type":"string"},"max_length":{"default":5000,"description":"Maximum number of characters to return.","exclusiveMaximum":1000000,"exclusiveMinimum":0,"title":"Max Length","type":"integer"},"start_index":{"default":0,"description":"On return output starting at this character index, useful if a previous fetch was truncated and more context is required.","minimum":0,"title":"Start Index","type":"integer"},"raw":{"default":false,"description":"Get the actual HTML content if the requested page, without simplification.","title":"Raw","type":"boolean"}},"required":["url"],"title":"Fetch","type":"object"}}]}}
2024-12-11 13:50:38.424077 INFO: package:ChatMcp/provider/mcp_server_provider.dart:119: mcp_server count: 2
2024-12-11 13:50:45.626098 INFO: package:ChatMcp/mcp/stdio/stdio_client.dart:116: 写入数据: {"jsonrpc":"2.0","method":"tools/list","id":"tool-list-1"}
2024-12-11 13:50:45.628386 INFO: package:ChatMcp/mcp/stdio/stdio_client.dart:116: 写入数据: {"jsonrpc":"2.0","method":"tools/list","id":"tool-list-1"}
2024-12-11 13:50:45.632566 INFO: package:ChatMcp/page/layout/chat_page/chat_page.dart:147: tools:
{
  "sqlite": [
    {
      "name": "read-query",
      "description": "Execute a SELECT query on the SQLite database",
      "inputSchema": {
        "type": "object",
        "properties": {
          "query": {
            "type": "string",
            "description": "SELECT SQL query to execute"
          }
        },
        "required": [
          "query"
        ]
      }
    },
    {
      "name": "write-query",
      "description": "Execute an INSERT, UPDATE, or DELETE query on the SQLite database",
      "inputSchema": {
        "type": "object",
        "properties": {
          "query": {
            "type": "string",
            "description": "SQL query to execute"
          }
        },
        "required": [
          "query"
        ]
      }
    },
    {
      "name": "create-table",
      "description": "Create a new table in the SQLite database",
      "inputSchema": {
        "type": "object",
        "properties": {
          "query": {
            "type": "string",
            "description": "CREATE TABLE SQL statement"
          }
        },
        "required": [
          "query"
        ]
      }
    },
    {
      "name": "list-tables",
      "description": "List all tables in the SQLite database",
      "inputSchema": {
        "type": "object",
        "properties": {}
      }
    },
    {
      "name": "describe-table",
      "description": "Get the schema information for a specific table",
      "inputSchema": {
        "type": "object",
        "properties": {
          "table_name": {
            "type": "string",
            "description": "Name of the table to describe"
          }
        },
        "required": [
          "table_name"
        ]
      }
    },
    {
      "name": "append-insight",
      "description": "Add a business insight to the memo",
      "inputSchema": {
        "type": "object",
        "properties": {
          "insight": {
            "type": "string",
            "description": "Business insight discovered from data analysis"
          }
        },
        "required": [
          "insight"
        ]
      }
    }
  ],
  "fetch": [
    {
      "name": "fetch",
      "description": "Fetches a URL from the internet and optionally extracts its contents as markdown.\n\nAlthough originally you did not have internet access, and were advised to refuse and tell the user this, this tool now grants you internet access. Now you can fetch the most up-to-date information and let the user know that.",
      "inputSchema": {
        "description": "Parameters for fetching a URL.",
        "properties": {
          "url": {
            "description": "URL to fetch",
            "format": "uri",
            "minLength": 1,
            "title": "Url",
            "type": "string"
          },
          "max_length": {
            "default": 5000,
            "description": "Maximum number of characters to return.",
            "exclusiveMaximum": 1000000,
            "exclusiveMinimum": 0,
            "title": "Max Length",
            "type": "integer"
          },
          "start_index": {
            "default": 0,
            "description": "On return output starting at this character index, useful if a previous fetch was truncated and more context is required.",
            "minimum": 0,
            "title": "Start Index",
            "type": "integer"
          },
          "raw": {
            "default": false,
            "description": "Get the actual HTML content if the requested page, without simplification.",
            "title": "Raw",
            "type": "boolean"
          }
        },
        "required": [
          "url"
        ],
        "title": "Fetch",
        "type": "object"
      }
    }
  ]
}
2024-12-11 13:50:46.782210 INFO: package:ChatMcp/mcp/stdio/stdio_client.dart:116: 写入数据: {"jsonrpc":"2.0","method":"tools/call","id":"tool-call-1733896246781","params":{"name":"read-query","arguments":{"query":"SELECT * FROM products WHERE price > 100"},"_meta":{"progressToken":0}}}
2024-12-11 13:50:46.937949 SEVERE: package:ChatMcp/page/layout/chat_page/chat_page.dart:291: Error: Exception: Stream completion failed: DioException [bad response]: This exception was thrown because the response has a status code of 400 and RequestOptions.validateStatus was configured to throw for this status code.
The status code of 400 has the following meaning: "Client error - the request contains bad syntax or cannot be fulfilled"
Read more about status codes at https://developer.mozilla.org/en-US/docs/Web/HTTP/Status
In order to resolve this exception you typically have either to verify and fix your request code or you have to fix the server code.

#0      OpenAIClient.chatStreamCompletion (package:ChatMcp/llm/openai_client.dart:147)
<asynchronous suspension>
#1      _ChatPageState._handleSubmitted (package:ChatMcp/page/layout/chat_page/chat_page.dart:258)
<asynchronous suspension>

日志见上面

**Comment by daodao97** [comment]
@zhouad 下载最新版试试呢, 这个看着不是最新的日志

**Comment by zhouad** [comment]
In order to resolve this exception you typically have either to verify and fix your request code or you have to fix the server code.
}, {role: user, content: 显示products中所有记录}, {role: assistant, tool_calls: [{id: call_read-query, type: function, function: {name: read-query, arguments: {"query":"SELECT * FROM products;"}}}]}, {role: tool, content: [{type: text, text: [{'id': 1, 'name': 'Widget', 'price': 19.99}, {'id': 2, 'name': 'Gadget', 'price': 29.99}, {'id': 3, 'name': 'Gizmo', 'price': 39.99}, {'id': 4, 'name': 'Smart Watch', 'price': 199.99}, {'id': 5, 'name': 'Wireless Earbuds', 'price': 89.99}, {'id': 6, 'name': 'Portable Charger', 'price': 24.99}, {'id': 7, 'name': 'Bluetooth Speaker', 'price': 79.99}, {'id': 8, 'name': 'Phone Stand', 'price': 15.99}, {'id': 9, 'name': 'Laptop Sleeve', 'price': 34.99}, {'id': 10, 'name': 'Mini Drone', 'price': 299.99}, {'id': 11, 'name': 'LED Desk Lamp', 'price': 45.99}, {'id': 12, 'name': 'Keyboard', 'price': 129.99}, {'id': 13, 'name': 'Mouse Pad', 'price': 12.99}, {'id': 14, 'name': 'USB Hub', 'price': 49.99}, {'id': 15, 'name': 'Webcam', 'price': 69.99}, {'id': 16, 'name': 'Screen Protector', 'price': 9.99}, {'id': 17, 'name': 'Travel Adapter', 'price': 27.99}, {'id': 18, 'name': 'Gaming Headset', 'price': 159.99}, {'id': 19, 'name': 'Fitness Tracker', 'price': 119.99}, {'id': 20, 'name': 'Portable SSD', 'price': 179.99}]}], name: read-query, tool_call_id: call_read-query}], stream: true} DioException [bad response]: This exception was thrown because the response has a status code of 400 and RequestOptions.validateStatus was configured to throw for this status code.
The status code of 400 has the following meaning: "Client error - the request contains bad syntax or cannot be fulfilled"
Read more about status codes at https://developer.mozilla.org/en-US/docs/Web/HTTP/Status
In order to resolve this exception you typically have either to verify and fix your request code or you have to fix the server code.

#0      OpenAIClient.chatStreamCompletion (package:ChatMcp/llm/openai_client.dart:152)
<asynchronous suspension>
#1      _ChatPageState._handleSubmitted (package:ChatMcp/page/layout/chat_page/chat_page.dart:258)
<asynchronous suspension>


还是会报错

**Comment by daodao97** [comment]
@zhouad 可以试试新版本

**Comment by nicolashw** [comment]
still exist. Exception: call openai chatStreamCompletion failed: endpoint: https://api.openai-proxy.live/chat/completions body: {model: gpt-4o-mini, messages: [{role: user, content: hi}], stream: true} DioException [bad response]: This exception was thrown because the response has a status code of 404 and RequestOptions.validateStatus was configured to throw for this status code. The status code of 404 has the following meaning: "Client error - the request contains bad syntax or cannot be fulfilled" Read more about status codes at https://developer.mozilla.org/en-US/docs/Web/HTTP/Status In order to resolve this exception you typically have either to verify and fix your request code or you have to fix the server code.

**Comment by daodao97** [comment]
> still exist. Exception: call openai chatStreamCompletion failed: endpoint: https://api.openai-proxy.live/chat/completions body: {model: gpt-4o-mini, messages: [{role: user, content: hi}], stream: true} DioException [bad response]: This exception was thrown because the response has a status code of 404 and RequestOptions.validateStatus was configured to throw for this status code. The status code of 404 has the following meaning: "Client error - the request contains bad syntax or cannot be fulfilled" Read more about status codes at https://developer.mozilla.org/en-US/docs/Web/HTTP/Status In order to resolve this exception you typically have either to verify and fix your request code or you have to fix the server code.

Maybe you need change you endpoint to `https://api.openai-proxy.live/v1`
